### ISSUE TITLE
Password authentication

### ISSUE THREAD

**Issue by Radiergummi** [OfficeDev/teamsfx-cli-action#21]
Do I read this right, and I'll need to put my account password into the config and disable MFA? There's so much OAuth fluff involved with getting a Teams app running, but at this crucial step we're supposed to throw it all overboard and have an unprotected account responsible for publishing new revisions of our app..?

Is this a temporary solution, or really the actual thing?

**Comment by heresandyboy** [comment]
I would also really appreciate an answer to this question. In the readme it is suggested that `login by device code will be supported in the future` has there been any progress on that? Or are we still expected to disable MFA on an 365 account in order to deploy the Teams App?

**Comment by heresandyboy** [comment]
I am actually deploying via Azure DevOps Pipelines, but as the documentation was very poor, I have used the readme from this Github action to help me figure out how to set this up.

After looking back over one of the samples for Azure Pipelines: 
https://github.com/OfficeDev/TeamsFx/blob/main/docs/cicd/azdo/publish.yml

I notice there is a env var for `CI_ENABLED` with a comment ` # To enable M365 account login by non-interactive mode. `

I wonder if that same env var can be used in this github action in order to enable deployment without having to disable MFA on the actual M365 account?

From the Azure Pipeline template example:

```yaml
- task: Bash@3
  env:
    M365_ACCOUNT_NAME: $(M365_ACCOUNT_NAME)
    M365_ACCOUNT_PASSWORD: $(M365_ACCOUNT_PASSWORD)
    M365_TENANT_ID: $(M365_TENANT_ID)
    # To enable M365 account login by non-interactive mode. 
    CI_ENABLED: 'true'
    # To specify the environment name which will be used as an option below.
    # You can change it to use your own environment name.
    TEAMSFX_ENV_NAME: 'dev'
    # To specify the version of TTK CLI for use.
    TEAMSFX_CLI_VERSION: 2.*
  inputs:
    targetType: 'inline'
    script: |
      set -evuxo pipefail
```
